export const INITIALIZE = "INITIALIZE";
export const ADD_ISSUE = "ADD_ISSUE";
export const DELETE_ISSUE = "DELETE_ISSUE";
export const FILTER_ISSUE = "FILTER_ISSUE";

export const TOGGLE_SEVERITY = "TOGGLE_SEVERITY";
export const TOGGLE_STATUS = "TOGGLE_STATUS";
export const TOGGLE_CREATED_DATE = "TOGGLE_CREATED_DATE";
export const TOGGLE_RESOLVED_DATE = "TOGGLE_RESOLVED_DATE";

export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";

export const REGISTER_USER = "REGISTER_USER";
