export const INITIALIZE = "INITIALIZE";
export const ADD_ISSUE = "ADD_ISSUE";
export const DELETE_ISSUE = "DELETE_ISSUE";

export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";

export const REGISTER_USER = "REGISTER_USER";
